# Stub file for matplotlib
# This is to help PyRight resolve matplotlib imports

from typing import Any

def use(backend: str) -> None: ...

class pyplot:
    @staticmethod
    def figure(figsize: tuple[float, float] | None = None) -> Any: ...
    @staticmethod 
    def subplots(nrows: int = 1, ncols: int = 1, figsize: tuple[float, float] | None = None) -> tuple[Any, Any]: ...
    @staticmethod
    def plot(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def xlabel(xlabel: str) -> None: ...
    @staticmethod
    def ylabel(ylabel: str) -> None: ...
    @staticmethod
    def title(label: str) -> None: ...
    @staticmethod
    def legend(*args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def grid(b: bool | None = None, **kwargs: Any) -> None: ...
    @staticmethod
    def tight_layout() -> None: ...
    @staticmethod
    def savefig(fname: str, **kwargs: Any) -> None: ...
    @staticmethod
    def pie(x: Any, labels: Any | None = None, autopct: str | None = None) -> Any: ...
    @staticmethod
    def suptitle(t: str, **kwargs: Any) -> Any: ...