# Stub file for numpy
# This is to help PyRight resolve numpy imports

from typing import Any

def array(object: Any, dtype: Any = None, copy: bool = True, order: str = "K", subok: bool = False, ndmin: int = 0) -> Any: ...

class ndarray:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def shape(self) -> tuple[int, ...]: ...
    def max(self) -> Any: ...
    def min(self) -> Any: ...
    def mean(self) -> Any: ...

class float64:
    def __init__(self, x: Any) -> None: ...
    def __float__(self) -> float: ...

def linspace(start: float, stop: float, num: int = 50, endpoint: bool = True, retstep: bool = False, dtype: Any = None, axis: int = 0) -> ndarray: ...
def arange(start: float, stop: float | None = None, step: float = 1, dtype: Any = None) -> ndarray: ...
def zeros(shape: Any, dtype: Any = None, order: str = "C") -> ndarray: ...
def ones(shape: Any, dtype: Any = None, order: str = "C") -> ndarray: ...
def sqrt(x: Any) -> Any: ...
def abs(x: Any) -> Any: ...
def max(a: Any, axis: Any = None) -> Any: ...
def min(a: Any, axis: Any = None) -> Any: ...
def sin(x: Any) -> Any: ...
def cos(x: Any) -> Any: ...
def var(a: Any, axis: Any = None, dtype: Any = None, ddof: int = 0) -> Any: ...

# Mathematical constants
pi: float