# Stub file for pandas
# This is to help PyRight resolve pandas imports

from typing import Any, Optional

class DataFrame:
    def __init__(self, data: Any = None, index: Any = None, columns: Any = None, dtype: Any = None, copy: bool = False) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def to_string(self, index: bool = True) -> str: ...
    def to_csv(self, path_or_buf: Any = None, sep: str = ",", na_rep: str = "", index: bool = True, encoding: str | None = None) -> None: ...
    @property
    def columns(self) -> Any: ...
    def max(self) -> Any: ...
    def min(self) -> Any: ...
    def mean(self) -> Any: ...
    @property
    def values(self) -> Any: ...

class Series:
    def __init__(self, data: Any = None, index: Any = None, dtype: Any = None, name: Any = None, copy: bool = False, fastpath: bool = False) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def max(self) -> Any: ...
    def min(self) -> Any: ...
    def mean(self) -> Any: ...
    @property
    def values(self) -> Any: ...